name: CD3 Project automation for Issues

on:
  issues:
    types: [labeled]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/oracle-devrel/projects/2/views/1
          github-token: ${{ secrets.PROJECT_AUTOMATION_TOKEN }}
